version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: bucket
          to: s3://my-s3-bucket-name/prefix
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: s3://my-s3-bucket-name
workflows:
  s3-example:
    jobs:
      - build

#version: 2.1
#orbs:
#  aws-s3: circleci/aws-s3@3.1
#jobs:
#  build:
#    docker:
#      - image: cimg/python:3.10
#    steps:
#      - checkout
#      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
#      - aws-s3/sync:
#          arguments: |
#            --acl public-read \
#            --cache-control "max-age=86400"
#      - persist_to_workspace:
#          root: .
#          paths:
#            - .
#  test:
#    docker:
#      - image: alpine:latest
#    steps:
#      - attach_workspace:
#          at: .
#      - checkout
#      - run: ./gradlew test
#      - persist_to_workspace:
#          root: .
#          paths:
#            - .
#  deploy:
#    docker:
#      - image: alpine:latest
#    steps:
#      - attach_workspace:
#          at: .
#      - checkout
#      - run: aws s3 sync ./app/build s3://yummzy

#workflows:
#  build_and_test:
#    jobs:
#      - test
#      - build:
#          requires:
#            - test
#  # fetching code from the repo
#  Fetch-Code:
#    docker:
#      - image: cimg/base:2021.04
#    steps:
#      - run:
#          name: Getting the Code
#          command: |
#            ls -al
#            echo '^^^Your repo files^^^'
#  # running a node container
#  Using-Node:
#    docker:
#      - image: cimg/node:17.2
#    steps:
#      - run:
#          name: Running the Node Container
#          command: |
#            node -v
#workflows:
#  Example-Workflow:
#    jobs:
#      - Hello-World
#      - Fetch-Code:
#          requires:
#            - Hello-World
#      - Using-Node:
#          requires:
#            - Fetch-Code
