version: 2.1
jobs:
  build:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          cd ./app
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./app/build s3://yummzy

#workflows:
#  build_and_test:
#    jobs:
#      - test
#      - build:
#          requires:
#            - test
#  # fetching code from the repo
#  Fetch-Code:
#    docker:
#      - image: cimg/base:2021.04
#    steps:
#      - run:
#          name: Getting the Code
#          command: |
#            ls -al
#            echo '^^^Your repo files^^^'
#  # running a node container
#  Using-Node:
#    docker:
#      - image: cimg/node:17.2
#    steps:
#      - run:
#          name: Running the Node Container
#          command: |
#            node -v
#workflows:
#  Example-Workflow:
#    jobs:
#      - Hello-World
#      - Fetch-Code:
#          requires:
#            - Hello-World
#      - Using-Node:
#          requires:
#            - Fetch-Code
