version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout
      - run:
          name: Title build job
          command: |
            echo "Build job started!"
            echo "This is the first build job"
  test:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout
      - run:
          name: Title test job
          command: |
            echo "Test job started!"
            echo "This is the first test job"
workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
#  # fetching code from the repo
#  Fetch-Code:
#    docker:
#      - image: cimg/base:2021.04
#    steps:
#      - run:
#          name: Getting the Code
#          command: |
#            ls -al
#            echo '^^^Your repo files^^^'
#  # running a node container
#  Using-Node:
#    docker:
#      - image: cimg/node:17.2
#    steps:
#      - run:
#          name: Running the Node Container
#          command: |
#            node -v
#workflows:
#  Example-Workflow:
#    jobs:
#      - Hello-World
#      - Fetch-Code:
#          requires:
#            - Hello-World
#      - Using-Node:
#          requires:
#            - Fetch-Code
